### ISSUE TITLE
InvalidBucketName: The specified bucket is not valid

### ISSUE THREAD

**Issue by OneMuppet** [serverless/serverless-client-s3#11]
I'm trying to deploy using environment variables: 
{
    "name": "aaaa_bbbb_cccc",
    "plugins": [
        "serverless-client-s3"
    ],
    "custom": {
        "client": {
            "bucketName": "aaaa_bbbb_cccc.${stage}.${region}"
        }
    }
}

This is what I get when I run the deploy, I'm guessing that the problem is that ${stage} and region doesn't get converted correctly?
###### 

Serverless: Deploying client to stage "development" in region "eu-west-1"...  
Serverless: / /Users/username/.node/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:49
        fn = function () { throw arg; };
                           ^

InvalidBucketName: The specified bucket is not valid.
    at Request.extractError (/Users/username/.node/lib/node_modules/serverless/node_modules/aws-sdk/lib/services/s3.js:334:35)
    at Request.callListeners (/Users/username/.node/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/Users/username/.node/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/username/.node/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:596:14)
    at Request.transition (/Users/username/.node/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:21:10)
    at AcceptorStateMachine.runTo (/Users/username/.node/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/username/.node/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/username/.node/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:37:9)
    at Request.<anonymous> (/Users/username/.node/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:598:12)
    at Request.callListeners (/Users/username/.node/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/Users/username/.node/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/username/.node/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:596:14)
    at Request.transition (/Users/username/.node/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:21:10)
    at AcceptorStateMachine.runTo (/Users/username/.node/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/username/.node/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/username/.node/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:37:9)
    at Request.<anonymous> (/Users/username/.node/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:598:12)
    at Request.callListeners (/Users/username/.node/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at callNextListener (/Users/username/.node/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:95:12)
    at IncomingMessage.onEnd (/Users/username/.node/lib/node_modules/serverless/node_modules/aws-sdk/lib/event_listeners.js:209:11)
    at emitNone (events.js:73:20)
    at IncomingMessage.emit (events.js:167:7)
From previous event:
    at ServerlessProviderAws.request (/Users/username/.node/lib/node_modules/serverless/lib/ProviderAws.js:65:14)
    at ClientDeploy.<anonymous> (/Users/username/Code/aaaa_bbbb_cccc/node_modules/serverless-client-s3/index.js:185:28)
From previous event:
    at ClientDeploy._processDeployment (/Users/username/Code/aaaa_bbbb_cccc/node_modules/serverless-client-s3/index.js:178:10)
From previous event:
    at ClientDeploy.clientDeploy (/Users/username/Code/aaaa_bbbb_cccc/node_modules/serverless-client-s3/index.js:50:10)
From previous event:
    at /Users/username/.node/lib/node_modules/serverless/lib/Serverless.js:181:31
    at Array.reduce (native)
    at /Users/username/.node/lib/node_modules/serverless/lib/Serverless.js:180:32
From previous event:
    at Serverless._execute (/Users/username/.node/lib/node_modules/serverless/lib/Serverless.js:178:12)
    at Serverless.actions.(anonymous function) (/Users/username/.node/lib/node_modules/serverless/lib/Serverless.js:424:20)
    at Serverless.command (/Users/username/.node/lib/node_modules/serverless/lib/Serverless.js:393:38)
    at /Users/username/.node/lib/node_modules/serverless/bin/serverless:19:16
    at processImmediate [as _immediateCallback](timers.js:384:17)
From previous event:
    at Object.<anonymous> (/Users/username/.node/lib/node_modules/serverless/bin/serverless:18:4)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Function.Module.runMain (module.js:431:10)
    at startup (node.js:141:18)
    at node.js:977:3

**Comment by OneMuppet** [comment]
Sorry I should have tested better the problem was the low dashes.
![image](https://cloud.githubusercontent.com/assets/4235764/14231258/72b20c80-f97c-11e5-918f-26d7af93d67a.png)
