### ISSUE TITLE
client deploy exception

### ISSUE THREAD

**Issue by dwtowner** [serverless/serverless-client-s3#23]
The `client deploy' command has started to go wrong. The error message attached below is now appearing. It had been working fine and there's nothing in the output between the last successful deploy and the failing deploy to suggest anything that is wrong. If I log in to the AWS S3 console then that bucket is completely empty.

Is there any way that I can recover from this?

serverless version is 0.5.5 and client-s3 is 2.0.0

thanks,

dan.

---

/home/dant/serverless/bookings-beta/node_modules/serverless-client-s3/index.js:242
            return stats.isDirectory()
                        ^

TypeError: Cannot read property 'isDirectory' of undefined
    at ClientDeploy.<anonymous> (/home/dant/serverless/bookings-beta/node_modules/serverless-client-s3/index.js:242:25)
    at wrapper (/home/dant/serverless/bookings-beta/node_modules/serverless-client-s3/node_modules/lodash/lodash.js:4357:19)
    at FSReqWrap.oncomplete (fs.js:82:15)

**Comment by dwtowner** [comment]
I found a work around. I removed the local directory, did a client deploy, then moved the directory back and deployed again. Everything works again now. it would be good to know what went wrong though, and how to avoid it happening again.
