### ISSUE TITLE
Any plans to support the new version of serverless anytime soon? 

### ISSUE THREAD

**Issue by ChenLi0830** [serverless/serverless-client-s3#47]
Hello, thank you for the plugin. 😃  I am wondering if you have any plans to support the new version of serverless anytime soon? I am currently using Serverless 1.3 and get the following error when try to run `sls client deploy`. 

```
TypeError: S.getServerlessPath is not a function
    at new module.exports.S.classes.Plugin._prompt (/Users/Chen/Developer/Repository/GitMax/node_modules/serverless-client-s3/index.js:5:30)
    at PluginManager.addPlugin (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:28:28)
    at /usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:61:12
    at Array.forEach (native)
    at PluginManager.loadPlugins (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:58:13)
    at PluginManager.loadServicePlugins (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:86:10)
    at PluginManager.loadAllPlugins (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:54:10)
    at /usr/local/lib/node_modules/serverless/lib/Serverless.js:64:28
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
 
     Please report this error. We think it might be a bug.
 
  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       4.6.2
     Serverless Version: 1.3.0

```

Here is the `plugin` section of the serverless.yml file
```
plugins:
  - serverless-client-s3

custom:
  client:
    bucketName: my.bucket.name

```

**Comment by kevzettler** [comment]
support is working in this thread https://github.com/serverless/serverless-client-s3/pull/43
